
//					Copyright Gavin Band 2008 - 2012.
// Distributed under the Boost Software License, Version 1.0.
//		(See accompanying file LICENSE_1_0.txt or copy at
//					http://www.boost.org/LICENSE_1_0.txt)

#include "../package_revision_autogenerated.hpp"

#include <set>
#include <memory>
#include <boost/ptr_container/ptr_vector.hpp>
#include <boost/unordered_set.hpp>
#include <boost/filesystem.hpp>
#include <boost/noncopyable.hpp>
#include <boost/optional.hpp>
#include <boost/optional/optional_io.hpp>
#include <boost/function.hpp>
#include <boost/format.hpp>
#include <boost/random.hpp>
#include <boost/bimap.hpp>
#include <boost/bimap/unordered_set_of.hpp>
#include <boost/bimap/unordered_multiset_of.hpp>

#include <boost/random/gamma_distribution.hpp>

#include <Eigen/Core>

// seqlib
#include "SeqLib/RefGenome.h"
#include "SeqLib/BamReader.h"
#include "SeqLib/GenomicRegionCollection.h"
#include "SeqLib/GenomicRegion.h"
//#include "SeqLib/BWAWrapper.h"

namespace seqlib = SeqLib;
// namespace bt = BamTools ;

// Alignment
#include "bindings/cpp/WFAligner.hpp"
#include "ssw_cpp.h"

// Queue
#include "concurrentqueue/concurrentqueue.h"

//
#include "appcontext/appcontext.hpp"
#include "genfile/GenomePositionRange.hpp"
#include "genfile/string_utils/string_utils.hpp"
#include "genfile/string_utils/slice.hpp"
#include "genfile/Error.hpp"
#include "genfile/Fasta.hpp"
#include "genfile/FileUtils.hpp"
#include "genfile/reverse_complement.hpp"
#include "genfile/translate.hpp"
#include "statfile/BuiltInTypeStatSink.hpp"
#include "iorek/log_sum_exp.hpp"

#define DEBUG 1

namespace globals {
	std::string const program_name = "translatorator" ;
	std::string const program_version = package_version ;
	std::string const program_revision = std::string( package_revision ).substr( 0, 7 ) ;
}

struct TranslatoratorOptionProcessor: public appcontext::CmdLineOptionProcessor
{
public:
	std::string get_program_name() const { return globals::program_name ; }

	void declare_options( appcontext::OptionProcessor& options ) {
		// Meta-options
		options.set_help_option( "-help" ) ;
		
		options.declare_group( "Input file options" ) ;
		options[ "-sequences" ]
			.set_description( "Path of FASTA file, or of BAM/CRAM files to operate on.  Note that this program expects to see "
			"long DNA sequences that cover the full translated length of the target protain" )
			.set_takes_values_until_next_option()
			.set_is_required()
		;
		options[ "-range" ]
			.set_description(
				"Ignore reads that don't overlap the this range of positions (in the form <chromosome>:<position>, or <chromosome>:<start>-<end>). "
				"(Note " + globals::program_name + " uses 1-based coordinates with closed intervals.)"
				" This option implies using an indexed BAM, SAM or CRAM file as input to -sequences." )
			.set_takes_values_until_next_option()
			.set_minimum_multiplicity( 0 )
			.set_maximum_multiplicity( 1000 )
		;

		options[ "-reference" ]
			.set_description( "Specify reference sequence (mandatory when using CRAM files)" )
			.set_takes_single_value() ;
		
		options[ "-exclude-reads" ]
			.set_description( "Specify a file of read IDs to exclude from the analysis" )
			.set_takes_single_value()
		;

		options.declare_group( "Output file options" ) ;
		options[ "-output-clusters" ]
			.set_description( "Path of main clusters output file." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-output-sequences" ]
			.set_description( "Output a tsv file detailing the input sequences." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-output-alignments" ]
			.set_description( "Path of per-alignment output file." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-output-identities" ]
			.set_description( "Path of hpc-to-cluster identities output file." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-summary" ]
			.set_description( "Path to per-sample summary output file." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-dna-fasta" ]
			.set_description( "Path to FASTA output file for DNA sequences." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options[ "-aa-fasta" ]
			.set_description( "Path to FASTA output file for AA sequences." )
			.set_takes_single_value()
			.set_default_value( "-" ) ;

		options.declare_group( "Coding sequence options" ) ;
		options[ "-cds-kmers" ]
			.set_description(
				"Specify a pair of DNA kmers, on the *translation strand*, that represent the start and end of a CDS segment."
				" If the gene has multiple exons, specify this option multiple times."
			)
			.set_takes_values_until_next_option()
			.set_minimum_multiplicity(1)
			.set_minimum_multiplicity(1000) ;

		options.declare_group( "Algorithm options" ) ;
		options[ "-cluster" ]
			.set_description( "Generate a list of candidate correct sequences, and align all reads back to candidates to cluster them. "
			"Then output corrected DNA and amino acid sequences" )
		;
		options[ "-iterations" ]
			.set_description( "Number of iterations" )
			.set_takes_single_value()
			.set_default_value( 1 )
		;
		options[ "-min-obs-per-sample" ]
			.set_description( "The minimum number of times a sequence must be observed in one sample, "
			" before it is treated as a candidate for clustering." )
			.set_takes_single_value()
			.set_default_value( 1 )
		;
		options[ "-min-fraction-per-sample" ]
			.set_description( "The minimum fraction of sequences must be observed in one sample, "
			" before it is treated as a candidate for clustering." )
			.set_takes_single_value()
			.set_default_value( 0 )
		;
		options[ "-min-obs-samples" ]
			.set_description( "The minimum number of samples a sequence must be observed in,"
			" before it is treated as a candidate for clustering." )
			.set_takes_single_value()
			.set_default_value( 1 )
		;
		options[ "-only-translatable" ]
			.set_description( "Only use sequences that are a multiple of 3 in length to cluster." )
		;
		options[ "-truncate-at-stops" ]
			.set_description( "Specify that aa sequences will be truncated at stop codons." )
		;
		options[ "-homopolymer-indel-weight" ]
			.set_description( "Alter weight of homopolymer length errors in the likelihood computation. "
				"A value of zero means homopolymer length errors will be entirely disregarded (which in effect means "
				"that haplotypes differing by homopolymer contractions/expansions will be treated as the same.) "
				"A value of one treats homopolymer contractions/expansions like any other insertion/deletion."
			)
			.set_takes_single_value()
			.set_default_value(0.0) ;
		options[ "-min-alignment-identity" ]
			.set_description( "When summarising reads aligned to candidate correct sequences, "
			" only accept alignments with this minimum proportion of matching bases compared to alignment length" )
			.set_takes_single_value()
			.set_default_value( 0.95 )
		;

		options.option_implies_option( "-min-obs-per-sample", "-cluster" ) ;
		options.option_implies_option( "-min-obs-samples", "-cluster" ) ;
		options.option_implies_option( "-min-fraction-per-sample", "-cluster" ) ;

		options.option_excludes_option( "-only-translatable", "-truncate-at-stops" ) ;

		options.declare_group( "Other options" ) ;
		options[ "-threads" ]
			.set_description( "Number of threads to use to load kmers with. " )
			.set_takes_single_value()
			.set_default_value( 1 )
		;
//		options[ "-debug" ]
//			.set_description( "Print out debug information" )
//		;

	}
} ;

namespace impl {
	struct SequenceProvider: public boost::noncopyable {
		typedef std::unique_ptr< SequenceProvider > UniquePtr ;
		static UniquePtr open( std::string const& filename ) ;
		virtual ~SequenceProvider() {}

		virtual bool next(
			std::string* name,
			std::string* sequence,
			std::string* qualities = 0
		) = 0 ;
	} ;

	struct BamSequenceProvider: public SequenceProvider {
	public:
		typedef std::unique_ptr< BamSequenceProvider > UniquePtr ;
	public:
		static UniquePtr open( std::string const& filename ) {
			return UniquePtr(
				new BamSequenceProvider( filename )
			) ;
		}

		static UniquePtr open( std::string const& filename, std::string const& reference ) {
			return UniquePtr(
				new BamSequenceProvider( filename, reference )
			) ;
		}

		BamSequenceProvider( std::string const& filename ):
			m_filename( filename )
		{
			open_bam( filename ) ;
		}

		BamSequenceProvider( std::string const& filename, std::string const& reference ):
			m_filename( filename )
		{
			// assert if not CRAM file
			// This is because SeqLib has a dangerous crashing bug in that case.
			assert( filename.substr( filename.size() - 5, 5 ) == ".cram" ) ;
			m_reader.SetCramReference( reference ) ;
			open_bam( filename ) ;
		}

		void set_region( genfile::GenomePositionRange region ) {
			// Note: seqlib takes 1-baed coordinates here and holds them 1-based internally
			// But it converts to 0-based to talk to htslib under the hood.
			// The alignments also come back as 0-based.
			m_reader.SetRegion( seqlib::GenomicRegion( region.toString(), m_header )) ;
		}

		bool next(
			std::string* name,
			std::string* sequence,
			std::string* qualities
		) {
			assert( name ) ;
			assert( sequence ) ;
			bool result = false ;
			while(
				(result = m_reader.GetNextRecord( m_alignment ))
				&& (
					m_alignment.SecondaryFlag()
					|| m_alignment.DuplicateFlag()
					|| m_alignment.QCFailFlag()
				)
			) {}
	
			if( result ) {
				name->assign( m_alignment.Qname() ) ;
				sequence->assign( m_alignment.Sequence() ) ;
				if( qualities ) {
					qualities->assign( m_alignment.Qualities() ) ;
				}
			}
			return result ;
		}

	private:
		std::string m_filename ;
		seqlib::BamReader m_reader ;
		seqlib::BamHeader m_header ;
		seqlib::BamRecord m_alignment ;

		void open_bam( std::string const& filename ) {
			if( !m_reader.Open( filename )) {
				throw genfile::BadArgumentError(
					"::BamSequenceProvider::open()",
					"filename=\"" + filename + "\"",
					"Failed to open BAM file."
				) ;
			}
			m_header = m_reader.Header() ;
		}
	} ;

	struct FastaSequenceProvider: public SequenceProvider {
	public:
		typedef std::unique_ptr< FastaSequenceProvider > UniquePtr ;
		static UniquePtr open( std::string const& filename ) {
			return UniquePtr(
				new FastaSequenceProvider( filename )
			) ;
		}

		FastaSequenceProvider( std::string const& filename ):
			m_filename( filename ),
			m_i(0)
		{
			m_fasta.add_sequences_from_file( filename ) ;
		}

		bool next(
			std::string* name,
			std::string* sequence,
			std::string* qualities
		) {
			if( m_i >= m_fasta.number_of_sequences() ) {
				return false ;
			}
			std::string sequence_name = m_fasta.sequence_ids()[m_i] ;
			m_fasta.get_sequence( sequence_name, &m_data ) ;
			name->assign( sequence_name ) ;
			sequence->assign( m_data.begin(), m_data.end() ) ;
			if( qualities ) {
				// FASTA format
				// Make them have very high quality.
				qualities->assign( sequence->size(), '{' ) ;
			}
			++m_i ;
			return true ;
		}

		private:
			std::string m_filename ;
			std::size_t m_i ;
			genfile::Fasta m_fasta ;
			std::deque< char > m_data ;
	} ;

	SequenceProvider::UniquePtr SequenceProvider::open( std::string const& filename ) {
		SequenceProvider::UniquePtr result ;
		auto uf = genfile::uniformise( filename ) ;
		if( uf.first == "bam" || uf.first == "sam" || uf.first == "cram" ) {
			result = BamSequenceProvider::open( filename ) ;
		} else if( uf.first == "fasta" ) {
			result = FastaSequenceProvider::open( filename ) ;
		} else {
			throw genfile::BadArgumentError(
				"impl::SequenceProvider::open()",
				"filename=\"" + filename + "\"",
				"This doesn't look like a FASTA or BAM/SAM/CRAM file!"
			) ;
		}
		return result ;
	}

	struct KmerPair {
		KmerPair() {}

		KmerPair( KmerPair const& other ):
			m_start( other.m_start ),
			m_end( other.m_end )
		{}

		KmerPair( std::string const& a, std::string const& b ):
			m_start(a),
			m_end(b)
		{}

		KmerPair& operator=( KmerPair const& pair ) {
			m_start = pair.m_start ;
			m_end = pair.m_end ;
			return *this ;
		}

		std::string const& first() const { return m_start ; }
		std::string const& second() const { return m_end ; }

		private:

		std::string m_start ;
		std::string m_end ;
	} ;

	struct SegmentedSequence {
		public:
			struct Range {
				Range(): start(0), end(0) {} ;
				Range( Range const& other ) = default ;
				Range( std::size_t _start, std::size_t _end ):
					start( _start ),
					end( _end )
				{}

				bool operator==( Range const& other ) const {
					return (start == other.start && end == other.end ) ;
				}

				bool operator<( Range const& other ) const {
					return ((start < other.start) || ((start == other.start) && (end < other.end) )) ;
				}

				std::size_t length() const { return end - start ; }

				std::size_t start ;
				std::size_t end ;
			} ;

			typedef std::vector< Range > Ranges ;

			SegmentedSequence( SegmentedSequence const& other ):
				m_sequence( other.m_sequence ),
				m_ranges( other.m_ranges )
			{}
			SegmentedSequence() = default ;
			SegmentedSequence(
				std::string const& sequence,
				Ranges const& ranges
			):
				m_sequence( sequence ),
				m_ranges( ranges )
			{}

			bool operator==( SegmentedSequence const& b ) const {
				return (m_sequence == b.m_sequence) && (m_ranges == b.m_ranges) ;
			}

			bool operator<( SegmentedSequence const& b ) const {
				return (m_sequence < b.m_sequence) || ((m_sequence == b.m_sequence) && (m_ranges < b.m_ranges)) ;
			}

			std::string const& matching_sequence() const { return m_sequence ; }
			std::string hpc_sequence() const {
				std::string result ;
				// homopolymer compress, but only within the ranges.
				result.reserve( m_sequence.size() ) ;
				std::size_t i = 0 ;
				for( auto range: m_ranges ) {
					if( result.size() > 0 ) {
						result.push_back( '_' ) ;
					}
					char last = ' ' ;
					for( ; range.start != range.end; ++range.start, ++i ) {
						if( m_sequence[i] != last ) {
							result.push_back(m_sequence[i]) ;
							last = result.back() ;
						}
					}
				}
				return result ;
			}
			Ranges const& ranges() const { return m_ranges ; }
			std::string const& sequence() const { return m_sequence ; }

			private:
			std::string m_sequence ;
			Ranges m_ranges ;
	} ;

	std::ostream& operator<<( std::ostream& out, SegmentedSequence const& ss ) {
		std::size_t pos = 0 ;
		for( std::size_t i = 0; i < ss.ranges().size(); ++i ) {
			std::size_t length = ss.ranges()[i].length() ;
			if( i > 0 ) {
				out << "..." ;
			}
			out << ss.sequence().substr( pos, length ) ;
			pos += length ;
		}
		return out ;
	}

	template< typename Elt >
	std::ostream& operator<<( std::ostream& out, std::vector< Elt > const& v ) {
		for( std::size_t i = 0; i < v.size(); ++i ) {
			if( i > 0 ) {
				out << ";" ;
			}
			out << v[i] ;
		}
		return out ;
	}

	// A 'segmentation' is used to keep track of the positions of stated kmers within
	// an input sequence, such as a read.
	struct Segmentation {
		public:
			enum Strand {
				eAmbiguousStrand = '?',
				eFwdStrand       = '+',
				eRevStrand       = '-',
				eNeitherStrand   = 'n',
				// TODO: Conceptually, excluded reads should be handled elsewhere, but at
				// the moment it is convenient to allow them to be handled here.
				eExcluded        = 'x'
			} ;
			typedef SegmentedSequence::Range Range ;
			typedef SegmentedSequence::Ranges Ranges ;

			Segmentation() {}

			Segmentation(
				std::string const& name,
				std::string const& sequence_name,
				Strand const strand,
				SegmentedSequence const& sequence
			):
				m_name( name ),
				m_sequence_name( sequence_name ),
				m_strand( strand ),
				m_sequence( sequence )
			{}

			// legacy
			Segmentation(
				std::string const& name,
				std::string const& sequence_name,
				Strand const strand,
				std::string const& sequence,
				std::vector< SegmentedSequence::Range > ranges
			):
				m_name( name ),
				m_sequence_name( sequence_name ),
				m_strand( strand ),
				m_sequence( SegmentedSequence( sequence, ranges ))
			{}

			Segmentation( Segmentation const& other ):
				m_name( other.m_name ),
				m_sequence_name( other.m_sequence_name ),
				m_strand( other.m_strand ),
				m_sequence( other.m_sequence )
			{}

			std::string const& sample_id() const { return m_name ; }
			std::string const& sequence_id() const { return m_sequence_name ; }
			SegmentedSequence const& sequence() const { return m_sequence ; }
			Strand const strand() const { return m_strand ; }
			bool is_unambiguous() const { return m_strand == eFwdStrand || m_strand == eRevStrand ; }
			std::string const& matching_sequence() const { return m_sequence.matching_sequence() ; }
			std::string hpc_sequence() const { return m_sequence.hpc_sequence() ; }
			Ranges const& ranges() const { return m_sequence.ranges() ; }

		private:
			std::string m_name ;
			std::string m_sequence_name ;
			Strand m_strand ;
			SegmentedSequence m_sequence ;
	} ;

	struct AlignmentOpScores {
		// match scores, by position in homopolymer, must be size 16.
		Eigen::VectorXi match ;
		int mismatch ;
		int gap1_open ;
		int gap1_extend ;
		int gap2_open ;
		int gap2_extend ;
	} ;

	std::ostream& operator<<( std::ostream& out, AlignmentOpScores const& scores ) {
		return out << "=:" << scores.match
			<< " X:" << scores.mismatch
			<< " O:" << scores.gap1_open
			<< " E:" << scores.gap1_extend
			<< " O2:" << scores.gap2_open
			<< " E2:" << scores.gap2_extend
		;
	}

	struct AlignmentDetail {
		AlignmentOpScores op_scores ;
		std::string a ;
		std::string b ;
		double score ;
		double identity ;
		std::string long_form_cigar ;
		std::string cigar ;
		std::string aligned_a ;
		std::string aligned_b ;
		Eigen::RowVectorXi matches ;
		int mismatches ;
		int insertions ;
		int insertion_extensions ;
		int deletions ;
		int deletion_extensions ;
		int homopolymer_expansions ;
		int homopolymer_expansion_extensions ;
		int homopolymer_contractions ;
		int homopolymer_contraction_extensions ;

		AlignmentDetail():
			op_scores( AlignmentOpScores() ),
			score(0),
			identity(0.0),
			matches(Eigen::RowVectorXi::Constant( 16, 0 )),
			mismatches(0),
			insertions(0),
			insertion_extensions(0),
			deletions(0),
			deletion_extensions(0),
			homopolymer_expansions(0),
			homopolymer_expansion_extensions(0),
			homopolymer_contractions(0),
			homopolymer_contraction_extensions(0)
		 {}

		AlignmentDetail(
			AlignmentOpScores const& _op_scores,
			std::string const& _a,
			std::string const& _b,
			double _score,
			std::string const& _cigar
		):
			op_scores( _op_scores ),
			a( _a ),
			b( _b ),
			score( _score ),
			identity( 0.0 ),
			long_form_cigar( _cigar ),
			cigar( runlength_encode(_cigar) ),
			matches(Eigen::RowVectorXi::Constant( 16, 0 )),
			mismatches(0),
			insertions(0),
			insertion_extensions(0),
			deletions(0),
			deletion_extensions(0),
			homopolymer_expansions(0),
			homopolymer_expansion_extensions(0),
			homopolymer_contractions(0),
			homopolymer_contraction_extensions(0)
		{
			aligned_a.reserve( a.size() + 25 ) ;
			aligned_b.reserve( b.size() + 25 ) ;
			std::size_t sa = 0, sb = 0 ;
			struct HomopolymerTract {
				HomopolymerTract(): start(0), end(0) {}
				HomopolymerTract(
					std::string const& sequence,
					std::size_t start_
				):
					start( start_ ),
					end( 0 )
				{
					for(
						end = start ;
						sequence[end] == sequence[start];
						++end
					) ;
				}
				std::size_t start ;
				std::size_t end ;
				std::size_t length() const { return end - start ; }
			} ;
			// a  = sequence of read (query)
			// sa = position in a
			// b  = sequence of template to align to
			// sb = position in b
			HomopolymerTract left_homopolymer, right_homopolymer( b, 0 ) ;
			for( std::size_t i = 0; i < long_form_cigar.size(); ) {
				if( b[sb] != b[right_homopolymer.start] ) {
					// The base at index sb is in a new homopolymer tract, find it now.
					left_homopolymer = right_homopolymer ;
					right_homopolymer = HomopolymerTract( b, sb ) ;
				}
				//int const index_in_homopolymer = (sb - right_homopolymer.start) ;
				//int const max_index = (op_scores.match.size() - 1) ;
				char op = long_form_cigar[i] ;
				switch( op ) {
					case 'M':
					case '=':
//						++matches( std::min(index_in_homopolymer, max_index )) ;
						++matches(0) ;
						identity += 1.0 ;
						aligned_a.push_back( a[sa++] ) ;
						aligned_b.push_back( b[sb++] ) ;
						//long_form_cigar[i] = ( index_in_homopolymer == 0 ) ? 'M' : 'm' ;
						++i ;
						break ;
					case 'X':
						++mismatches ;
						aligned_a.push_back( a[sa++] ) ;
						aligned_b.push_back( b[sb++] ) ;
						++i ;
						break ;
					case 'D':
						{
							// find end of deletion, to compare to homopolymers
							std::size_t deletion_end = i+1 ;
							for( ; deletion_end < long_form_cigar.size() && long_form_cigar[deletion_end] == 'D'; ++deletion_end ) ;
							if(
								right_homopolymer.length() > 1                       // in a homopolymer tract length>1
								&& (deletion_end-i) <= (right_homopolymer.end - sb)   // deletion contained in homopolymer
							) {
								++homopolymer_contractions ;
								for( ; i < deletion_end; ++i ) {
									long_form_cigar[i] = 'd' ;
									++homopolymer_contraction_extensions ;
									aligned_a.push_back( '-' ) ;
									aligned_b.push_back( b[sb++] ) ;
								}
							} else {
								++deletions ;
								for( ; i < deletion_end; ++i ) {
									++deletion_extensions ;
									aligned_a.push_back( '-' ) ;
									aligned_b.push_back( b[sb++] ) ;
								}
							}
						}
						break ;
					case 'I':
						{
							// find end of insertion, to compare to homopolymers
							std::size_t insertion_end = i+1 ;
							bool insertion_is_homopolymer = true ;
							for( std::size_t sai = sa; insertion_end < long_form_cigar.size() && long_form_cigar[insertion_end] == 'I'; ++insertion_end, ++sai ) {
								if( a[sai] != a[sa] ) {
									insertion_is_homopolymer = false ;
								}
							}
							if(
								insertion_is_homopolymer
								&& (
									(left_homopolymer.length() > 1 && a[sa] == b[left_homopolymer.start])
									|| (right_homopolymer.length() > 1 && a[sa] == b[right_homopolymer.start])
								)
							) {
								++homopolymer_expansions ;
								for( ; i < insertion_end; ++i ) {
									long_form_cigar[i] = 'i' ;
									++homopolymer_contraction_extensions ;
									aligned_a.push_back( a[sa++] ) ;
									aligned_b.push_back( '-' ) ;
								}
							} else {
								++insertions ;
								for( ; i < insertion_end; ++i ) {
									++insertion_extensions ;
									aligned_a.push_back( a[sa++] ) ;
									aligned_b.push_back( '-' ) ;
								}
							}
						}
						break ;
					default:
						assert(0) ;
				}
				assert( sa <= a.size() ) ;
				assert( sb <= b.size() ) ;
			}
			identity /= long_form_cigar.size() ;
			cigar = runlength_encode( long_form_cigar ) ;

			{
#if DEBUG
/*
				double my_score = (
					matches * op_scores.match
					+ mismatches * op_scores.mismatch
					+ (deletions+homopolymer_contractions+insertions+homopolymer_expansions) * op_scores.gap1_open
					+ (deletion_extensions+homopolymer_contraction_extensions+insertion_extensions+homopolymer_expansion_extensions) * op_scores.gap1_extend
				) ;

				if( my_score != score ) {
//					std::cerr << "!! AAARGH!  CIGAR=\"" << cigar << "\", score:" << score << " , my_score:" << my_score << ".\n" ;
					std::cerr << "!! M" << matches << " X" << mismatches
						<< " D" << (deletions)
						<< " HPD" << (homopolymer_contractions)
						<< " I" << (insertions)
						<< " HPI" << (homopolymer_expansions)
						<< " DD" << (deletion_extensions+homopolymer_contraction_extensions)
						<< " II" << (insertion_extensions+homopolymer_expansion_extensions)
						<< " AL" << aligned_a.size()
						<< " BL" << aligned_b.size()
						<< " LFCL" << long_form_cigar.size() << "\n" ;
//					std::cerr
//						<< "   " << long_form_cigar << "\n"
//						<< "   " << aligned_a << "\n"
//						<< "   " << aligned_b << "\n" ;
#endif
// !! AAARGH!  CIGAR="54M1X1507M2d559M", score:2106.0 , my_score:2105.0.
// !! M2119 X1 D0 HPD1 I0 HPI0 DD2 II0 LFCL2123
				}
*/
#endif
			}
		}

		double homopolymer_corrected_score( double homopolymer_weight = 0.0 ) const {
			return (
				(matches 																	* op_scores.match)(0)
				+ (mismatches 																* op_scores.mismatch)
				+ ((deletions+insertions) 													* op_scores.gap1_open)
				+ ((deletion_extensions+insertion_extensions) 								* op_scores.gap1_extend)
				+ ((homopolymer_contractions+homopolymer_expansions) 						* op_scores.gap1_open * homopolymer_weight)
				+ ((homopolymer_contraction_extensions+homopolymer_expansion_extensions) 	* op_scores.gap1_extend * homopolymer_weight)
			) ;
		}

	private:

		std::string runlength_encode( std::string const& long_form_cigar ) {
			std::string result ;
			if( long_form_cigar.size() == 0 ) {
				return long_form_cigar ;
			}
			char op = long_form_cigar[0] ;
			std::size_t i = 0 ;
			std::size_t count = 1 ;
			using genfile::string_utils::to_string ;
			for( i = 1; i < long_form_cigar.size(); ++i ) {
				if( long_form_cigar[i] == op ) {
					++count ;
				} else {
					result += to_string( count ) + op ;
					op = long_form_cigar[i] ;
					count = 1 ;
				}
			}
			result += to_string( count ) + op ;
			return result ;
		}
	} ;

	std::ostream& operator<<( std::ostream& out, AlignmentDetail const& a ) {
		return
		out << "len(A):" << a.a.size()
		<< " len(B):" << a.b.size()
		<< " AS:" << a.score
		<< " cigar:" << a.cigar
		<< " identity:" << a.identity
		<< " matches:" << a.matches
		<< " mismatches:" << a.mismatches
		<< " insertions:" << a.insertions
		<< " deletions:" << a.deletions
		<< " homopolymer expansions:" << a.homopolymer_expansions
		<< " homopolymer contractions:" << a.homopolymer_contractions ;
	}

	std::ostream& operator<<( std::ostream& out, Segmentation const& s ) {
		out
		<< "M[ "
		<< "\"" << s.sample_id() << "\" "
		<< "\"" << s.sequence_id() << "\" "
		<< std::string( 1, s.strand()) << " "
		;
		for( std::size_t i = 0; i < s.ranges().size(); ++i ) {
			out
				<< ((i>0) ? "," : "")
				<< s.ranges()[i].start
				<< "-"
				<< s.ranges()[i].end
			;
		}
		out << " ]" ;
		return out ;
	}

	void to_lower_inplace( std::string& s ) {
		std::transform(
			s.begin(), s.end(),
			s.begin(), [](unsigned char c) { return std::tolower(c) ; }
		) ;
	}

	void to_upper_inplace( std::string& s ) {
		std::transform(
			s.begin(), s.end(),
			s.begin(), [](unsigned char c) { return std::toupper(c) ; }
		) ;
	}
	std::string to_upper( std::string const& s ) {
		std::string result = s ;
		to_upper_inplace(result) ;
		return( result ) ;
	}

	bool load_fragmented_dna_sequence(
		std::string const& sequence,
		std::vector< KmerPair > const& kmer_pairs,
		std::string* result = 0,
		Segmentation::Ranges* ranges = 0
	) {
		std::string result_sequence ;
		Segmentation::Ranges positions ;
		// 
		for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
#if DEBUG > 1
			std::cerr << " sequence: \"" << sequence << "\".\n" ;
			std::cerr << "kmer pair: \"" << kmer_pairs[i].first() << "\", \"" << kmer_pairs[i].second() << "\".\n" ;
#endif
			std::size_t la = kmer_pairs[i].first().size() ;
			std::size_t lb = kmer_pairs[i].second().size() ;

			// Structural variants can create extra copies of exons that 
			// aren't part of transcribed genes. (E.g  exon 6/7 of Pf3D7_1127000 in Pf FUP/H).
			// Therefore, we only look downstream of the last found kmer pair.
			std::size_t const search_start_at = ( (i>0) ? positions[i-1].end + 1 : 0 ) ;

			int const a = sequence.find( kmer_pairs[i].first(), search_start_at ) ;
			int const b = sequence.find( kmer_pairs[i].second(), search_start_at ) ;
#if DEBUG > 1
			std::cerr << a << "(" << la << "), " << b << "(" << lb << ").\n" ;
#endif
			if( a == -1 || sequence.find( kmer_pairs[i].first(), a+1 ) != -1 ) {
				return false ;
			};
			if( b == -1 || sequence.find( kmer_pairs[i].second(), b+1 ) != -1 ) {
				return false ;
			};
#if DEBUG > 1
			std::cerr << "OK\n" ;
#endif
			// ensure b lies to the right of a,
			// and a..b lies to the right of anything seen previously.
			if(
				( b < (a+la))
				|| ((i>0) && a < ( positions[i-1].end ))
			) {
				return false ;
			} else {
				result_sequence += sequence.substr( a, b+lb-a ) ;
				positions.push_back( Segmentation::Range( a, b+lb ) ) ;
			}
		}
		if( result ) {
			*result = result_sequence ;
		}
		if( ranges ) {
			*ranges = positions ;
		}

#if DEBUG > 1
			std::cerr << "RESULT: \"" << result_sequence << "\".\n" ;
#endif
		return true ;
	}

	void test_load_fragmented_dna_sequence() {
		std::string sequence = "ACGTAACCGGTTAAACCCGGGTTTAAAACCCCGGGGTTTT" ;
		std::vector< KmerPair > pairs ;
		std::string result ;
		Segmentation::Ranges positions ;
		pairs.push_back( KmerPair( "CGTA", "GTTA" )) ;
		assert( !load_fragmented_dna_sequence( "", pairs, &result, &positions ) ) ;
		assert( !load_fragmented_dna_sequence( "CGTA", pairs, &result, &positions ) ) ;
		assert( load_fragmented_dna_sequence( "CGTAGTTA", pairs, &result, &positions ) ) ;
		assert( result.size() == 8 ) ;
		assert( positions.size() == 1 ) ;
		assert( load_fragmented_dna_sequence( "CGTAGTTAAAAA", pairs, &result, &positions ) ) ;
		assert( result.size() == 8 ) ;
		assert( positions.size() == 1 ) ;
		assert( load_fragmented_dna_sequence( "CGTAGCGCGCGCGGTTA", pairs, &result, &positions ) ) ;
		assert( result.size() == 17 ) ;
		assert( positions.size() == 1 ) ;
		assert( load_fragmented_dna_sequence( "CGTAGCGCGCGCGGTTAAAAA", pairs, &result, &positions ) ) ;
		assert( result.size() == 17 ) ;
		assert( positions.size() == 1 ) ;
		assert( !load_fragmented_dna_sequence( "CGTACGTAGTTA", pairs, &result, &positions ) ) ;
		assert( !load_fragmented_dna_sequence( "CGTAGTTAGTTA", pairs, &result, &positions ) ) ;
		assert( !load_fragmented_dna_sequence( "GTTACGTA", pairs, &result, &positions ) ) ;

		pairs.push_back( KmerPair( "GGTA", "GCTA" )) ;
		assert( !load_fragmented_dna_sequence( "CGTANGTTA", pairs, &result, &positions ) ) ;
		assert( !load_fragmented_dna_sequence( "CGTANGTTANGGTA", pairs, &result, &positions ) ) ;
		assert( load_fragmented_dna_sequence( "CGTANGTTANGGTANGCTA", pairs, &result, &positions ) ) ;
		assert( result.size() == 18 ) ;
		assert( positions.size() == 2 ) ;
		assert( !load_fragmented_dna_sequence( "CGTAGGTAGTTAGCTA", pairs, &result, &positions ) ) ;
		assert( !load_fragmented_dna_sequence( "CGTAGCTAGTTAGGTA", pairs, &result, &positions ) ) ;
	}

	struct MixtureOfHaplotypes {
		typedef std::size_t SequenceIndex ;
		typedef std::map< SequenceIndex, double > Haplotypes ;
		typedef boost::random::mt19937 RNG ;
		MixtureOfHaplotypes() {}

		std::size_t size() const { return m_haplotypes.size() ; }

		void visit( boost::function< void( SequenceIndex, double ) > callback ) const {
			for( auto& kv: m_haplotypes ) {
				callback( kv.first, kv.second ) ;
			}
		}

		std::vector< SequenceIndex > haplotypes() const {
			std::vector< SequenceIndex > result ;
			result.reserve( m_haplotypes.size() ) ;
			for( auto const kv: m_haplotypes ) {
				result.push_back( kv.first ) ;
			}
			return( result ) ;
		}

		// perturb all the weights.
		MixtureOfHaplotypes resample_weights(
			// boost random generator object
			RNG& rng,
			// controls how close to current mean values are.  Larger values mean less variation.
			double lambda = 5.0
		) {
			MixtureOfHaplotypes result = *this ;
			// Dirichlet sampling centred on the current weights.
			// Dirichlet sampling can be done by sampling from independent Gammas, and renormalising
			// https://en.wikipedia.org/wiki/Dirichlet_distribution#Random_variate_generation
			double total_weight = 0.0 ;
			for( auto& kv: result.m_haplotypes ) {
				boost::random::gamma_distribution< double > G ( kv.second * lambda, 1.0 ) ;
				kv.second = G( rng ) ;
				total_weight += kv.second ;
			}
			for( auto& kv: result.m_haplotypes ) {
				kv.second /= total_weight ;
			}
			return result ;
		}

		// Replace the ith haplotype without changing weights
		MixtureOfHaplotypes replace( SequenceIndex current_haplotype_, SequenceIndex new_haplotype ) {
			MixtureOfHaplotypes result = *this ;
			Haplotypes::iterator i = result.m_haplotypes.find(current_haplotype_) ;
			assert( i != result.m_haplotypes.end() ) ;
			auto weight = i->second ;
			result.m_haplotypes[ new_haplotype ] += weight ;
			result.m_haplotypes.erase( i ) ;
			return result ;
		}

		// Add a new haplotype to our list, scaling down all others by (1 - weight).
		MixtureOfHaplotypes add( SequenceIndex haplotype, double const weight = 0.1 ) {
			assert( weight >= 0.0 && weight <= 1.0 ) ;
			MixtureOfHaplotypes result = *this ;
			for( Haplotypes::iterator i = result.m_haplotypes.begin(); i != result.m_haplotypes.end() ; ++i ) {
				i->second *= (1.0 - weight) ;
			}
			result.m_haplotypes[ haplotype ] += weight ;
			return result ;
		}

		// Remove the ith haplotype from our list
		MixtureOfHaplotypes remove( SequenceIndex haplotype ) {
			MixtureOfHaplotypes result = *this ;
			Haplotypes::iterator i = result.m_haplotypes.find( haplotype ) ;
			assert( i != result.m_haplotypes.end() ) ;
			auto weight = i->second ;
			result.m_haplotypes.erase( i ) ;
			for( i = result.m_haplotypes.begin(); i != result.m_haplotypes.end() ; ++i ) {
				i->second /= (1.0 - weight) ;
			}
			return result ;
		}

		bool contains( SequenceIndex haplotype ) const {
			return m_haplotypes.find( haplotype ) != m_haplotypes.end() ;
		}

		std::ostream& serialise( std::ostream& out ) const {
			out << "MixtureOfHaplotypes: " ;
			for( auto kv: m_haplotypes ) {
				out << kv.first << ":" << std::setprecision(3) << kv.second << " " ;
			}
			return out ;
		}

/*
		std::size_t hash_value( MixtureOfHaplotypes const& state ) {
			std::size_t result = 0;
			boost::hash_combine( result, m_haplotypes.size() ) ;
			for( auto& kv: result.m_haplotypes ) {
				boost::hash_combine( result, kv.first ) ;
				boost::hash_combine( result, kv.second ) ;
			}
			return result ;
		}
*/
	private:
		// constains haplotype indices and weights
		// Invariant: weights always sum to 1.
		Haplotypes m_haplotypes ;

//			boost::random::mt19937 generator(random);
//			boost::random::beta_distribution<double> beta_random_dist(alpha, beta);
	} ;

	std::ostream& operator<<( std::ostream& out, MixtureOfHaplotypes const& state ) {
		return state.serialise(out) ;
	}


	struct AlgorithmData {
		struct SegmentationToReads {
			SegmentationToReads() = default ;
			SegmentationToReads( SegmentationToReads const& other ) = default ;
			SegmentationToReads(
				impl::SegmentedSequence _sequence,
				std::vector< impl::Segmentation > _reads
			):
				sequence( _sequence ),
				reads( _reads )
			{}
			impl::SegmentedSequence sequence ;
			std::vector< impl::Segmentation > reads ;

			friend std::ostream& operator<<( std::ostream& out, SegmentationToReads const& s ) ;
		} ;
		struct SequenceToIds {
			SequenceToIds() = default ;
			SequenceToIds( SequenceToIds const& other ) = default ;
			std::string sequence ;
			std::vector< std::size_t > sequence_ids ;
		} ;

		AlgorithmData( std::vector< Segmentation > const& segmentations ):
			m_unambiguous_read_count(0)
		{
			// For this algorithm we need:
			// 1. the input segmented sequences, ordered by the occurence count.
			std::map< impl::SegmentedSequence, std::vector< impl::Segmentation > > by_sequence_impl ;
			for( auto s: segmentations ) {
				if( s.is_unambiguous() ) {
					++m_unambiguous_read_count ;
					by_sequence_impl[ s.sequence() ].push_back( s ) ;
				} else {
					m_ambiguous_reads.push_back( s ) ;
				}
			}

			// Put sequences in descending order of frequency
			std::vector< SegmentationToReads > elts ;
			elts.reserve( by_sequence_impl.size() ) ;
			for( auto kv: by_sequence_impl ) {
				elts.push_back( SegmentationToReads( kv.first, kv.second )) ;
			}
			std::sort(
				elts.begin(),
				elts.end(),
				[]( SegmentationToReads const& a, SegmentationToReads const& b ) {
					return (a.reads.size() > b.reads.size()) || ((a.reads.size() == b.reads.size()) && (a.sequence < b.sequence)) ;
				}
			) ;

			std::vector< SequenceToIds > by_hpc_sequence ;
			std::map< std::string, std::size_t > found ;
			for( std::size_t i = 0; i < elts.size(); ++i ) {
				std::string hpc_sequence = elts[i].sequence.hpc_sequence() ;
				auto where = found.find( hpc_sequence ) ;
				if( where == found.end() ) {
					found[hpc_sequence] = by_hpc_sequence.size() ;
					by_hpc_sequence.push_back(
						SequenceToIds{
							hpc_sequence,
							std::vector< std::size_t >(1, i )
						}
					) ;
				} else {
					by_hpc_sequence[where->second].sequence_ids.push_back(i) ;
				}
			}

			m_sequences.swap( elts ) ;
			m_hpc_sequences.swap( by_hpc_sequence ) ;
		}

		std::size_t total_reads() const {
			return m_unambiguous_read_count + m_ambiguous_reads.size() ;
		}

		std::size_t total_unambiguous_reads() const {
			return m_unambiguous_read_count ;
		}

		std::vector< SegmentationToReads > const& sequences() const { return m_sequences ; }
		std::vector< Segmentation > const& ambiguous_sequences() const { return m_ambiguous_reads ; }
		std::vector< SequenceToIds > const& hpc_sequences() const { return m_hpc_sequences ; }

		std::size_t count_reads_for_hpc_sequence( std::size_t i ) const {
			std::size_t result = 0 ;
			for( std::size_t j: m_hpc_sequences[i].sequence_ids ) {
				result += m_sequences[j].reads.size() ;
			}
			return( result ) ;
		}


	private:
		std::vector< SegmentationToReads > m_sequences ;
		std::vector< SequenceToIds > m_hpc_sequences ;
		std::size_t m_unambiguous_read_count ;
		std::vector< Segmentation > m_ambiguous_reads ;
	} ;

	std::ostream& operator<<( std::ostream& out, AlgorithmData::SegmentationToReads const& s ) {
		out << s.sequence << ": " ;
		for( std::size_t i = 0; i < s.reads.size(); ++i ) {
			if( i>0 ) {
				out << "," ;
			}
			out << s.reads[i] ;
		}
		return( out ) ;
	}
}

struct TranslatoratorApplication: public appcontext::ApplicationContext
{
public:
	TranslatoratorApplication( int argc, char** argv ):
		appcontext::ApplicationContext(
			globals::program_name,
			globals::program_version + ", revision " + globals::program_revision,
			std::auto_ptr< appcontext::OptionProcessor >( new TranslatoratorOptionProcessor ),
			argc,
			argv,
			"-log"
		)
	{}
	
	void run() {
		try {
			impl::test_load_fragmented_dna_sequence() ;
			unsafe_process() ;
		}
		catch( genfile::InputError const& e ) {
			ui().logger() << "\nError (" << e.what() <<"): " << e.format_message() << ".\n" ;
			throw appcontext::HaltProgramWithReturnCode( -1 ) ;
		}
	}

private:
	
	typedef genfile::GenomePositionRange Region ;
	typedef std::vector< genfile::GenomePositionRange > Regions ;
	typedef impl::KmerPair KmerPair ;
	typedef impl::AlignmentDetail AlignmentDetail ;
	typedef impl::AlignmentOpScores AlignmentOpScores ;
	typedef std::string Sequence ;
	typedef std::string SampleId ;
	typedef impl::Segmentation Segmentation ;
	typedef impl::MixtureOfHaplotypes MixtureOfHaplotypes ;

	typedef std::size_t SequenceIndex ;
	typedef uint32_t SequenceCount ;
	struct Totals {
		Totals(): total(0), matched(0) {}
		SequenceCount total ;
		SequenceCount matched ;
	} ;
	typedef std::unordered_map< SampleId, Totals > PerSampleTotals ;
	typedef std::unordered_map< SequenceIndex, SequenceCount > SegmentationCounts ;
	typedef std::unordered_map< SampleId, std::unordered_map< SequenceIndex, SequenceCount > > PerSampleSequenceCounts ;
	typedef std::vector< std::vector< impl::Segmentation > > SegmentationsBySequence ;
	typedef impl::AlgorithmData AlgorithmData ;

	struct PairwiseAlignments {
		struct SequencePair {
			SequencePair( SequenceIndex from_ = 0, SequenceIndex to_ = 0 ):
				from( from_ ),
				to( to_ )
			{}
			SequenceIndex from ;
			SequenceIndex to ;

			bool operator<( SequencePair const& other ) const {
				return (from < other.from) || (from == other.from && to < other.to) ;
			}
		} ;
		typedef std::map< SequencePair, AlignmentDetail > Alignments ;

		void add_sequences(
			std::vector< AlgorithmData::SequenceToIds > const& sequences,
			boost::function< std::string ( AlgorithmData::SequenceToIds const& s ) > get_sequence,
			boost::function< bool( std::size_t ) > inclusion_filter,
			boost::function< void( std::size_t, std::size_t ) > progress = 0
		) {
			// These costs are from pbmm2 defaults https://github.com/PacificBiosciences/pbmm2:
			// - "CCS" or "HIFI" 
			// --mismatch-score 1
			// --mismatch-penalty 4 
			// --gap-open-1 6 
			// --gap-extend-1 2 
			// --gap-open-2 26 
			// --gap-extend-2 1
			Eigen::VectorXi match_scores = Eigen::VectorXi::Constant( 16, 0 ) ;
			match_scores(0) = 1 ;
			match_scores(1) = -1 ;
			match_scores(2) = -2 ;
			match_scores(3) = -3 ;
			AlignmentOpScores op_scores{
				  match_scores, // match
#if 0
				 -5, // mismatch
				 -7, // gap1 open
				 -3, // gap1 extend
				-27, // gap2 open
				 -2, // gap2 extend
#else
				 -4, // mismatch
				 -6, // gap1 open
				 -2, // gap1 extend
				-26, // gap2 open
				 -1, // gap2 extend
#endif
			} ;
			wfa::WFAlignerGapAffine2Pieces aligner(
				-op_scores.match(0),
				-op_scores.mismatch,
				-op_scores.gap1_open,
				-op_scores.gap1_extend,
				-op_scores.gap2_open,
				-op_scores.gap2_extend,
				wfa::WFAligner::Alignment,
				wfa::WFAligner::MemoryHigh
			) ;
			std::size_t alignment_count = 0 ;
			for( std::size_t j = 0; j < sequences.size(); ++j ) {
				if( inclusion_filter(j)) {
					m_targets.push_back(j) ;
				}
			}
			for( std::size_t i = 0; i < sequences.size(); ++i ) {
				for( std::size_t t = 0; t < m_targets.size(); ++t ) {
					std::size_t j = m_targets[t] ;
					auto from   = get_sequence( sequences[i] ) ;
					auto to     = get_sequence( sequences[j] ) ;
					auto status = aligner.alignEnd2End( to, from ) ;
					assert( status == WF_STATUS_SUCCESSFUL ) ;
					int score = aligner.getAlignmentScore() ;
					m_alignments[ SequencePair(i,j) ] = AlignmentDetail(
						op_scores,
						from,
						to,
						score,
						aligner.getAlignmentCigar()
					) ;
					if( progress ) {
						progress( ++alignment_count, m_targets.size() * sequences.size() ) ;
					}
				}
			}
		}

		std::size_t size() const { return m_alignments.size() ; }
		std::vector< SequenceIndex > const& alignment_targets() const { return m_targets ; }

		AlignmentDetail const& alignment(
			SequenceIndex from,
			SequenceIndex to
		) const {
			Alignments::const_iterator where = m_alignments.find( SequencePair( from, to )) ;
			assert( where != m_alignments.end() ) ;
			return where->second ;
		}

	private:
		Alignments m_alignments ;
		std::vector< SequenceIndex > m_targets ;
	} ;

	struct AlgorithmOptions {
		bool use_clustering ;
		bool only_translatable ;
		bool truncate_at_stops ;
		std::size_t number_of_threads ;
		std::size_t min_obs_per_sample ;
		double min_fraction_per_sample ;
		std::size_t max_clustering_iterations ;
		double homopolymer_indel_weight ;
		double min_identity ;
	} ;

	struct StateLL {
		MixtureOfHaplotypes state ;
		double ll ;
	} ;

	void unsafe_process() { 
		AlgorithmOptions algorithm_options = {
			options().check( "-cluster" ),
			options().check( "-only-translatable" ),
			options().check( "-truncate-at-stops" ),
			options().get< std::size_t >( "-threads" ),
			options().get< std::size_t >( "-min-obs-per-sample" ),
			options().get< double >( "-min-fraction-per-sample" ),
			options().get< std::size_t >( "-iterations" ),
			options().get< double >( "-homopolymer-indel-weight" ),
			options().get< double >( "-min-alignment-identity" )
		} ;
		unsafe_process( algorithm_options ) ;
	}

	void unsafe_process( AlgorithmOptions const& algorithm_options ) {
		std::vector< impl::KmerPair > kmer_pairs = load_kmer_pairs( options().get_values< std::string >( "-cds-kmers" ) ) ;
		std::unordered_set< std::string > excluded_reads ;
		if( options().check( "-exclude-reads" )) {
			load_excluded_reads( options().get< std::string >( "-exclude-reads" ), &excluded_reads ) ;
		}
		// A 'segmentation' means a set of sub-ranges of a sequence
		// which Segmentation the given kmer pairs.
		std::vector< Segmentation > segmentations ;
		find_segmentations(
			options().get_values< std::string >( "-sequences" ),
			[&excluded_reads]( std::string const& name, std::string const&, std::string const& ) {
				return excluded_reads.find( name ) == excluded_reads.end() ;
			},
			kmer_pairs,
			&segmentations
		) ;
		AlgorithmData data ( segmentations ) ;
		ui().logger() << "++ There were " << data.total_reads() << " total sequences...\n" ;
		ui().logger() << "++   of which " << data.total_unambiguous_reads() << " were unambiguously segmented.\n" ;
		ui().logger() << "++ There were " << data.sequences().size() << " distinct segmentations.\n" ;
		ui().logger() << "++ There were " << data.hpc_sequences().size() << " distinct compressed sequences.\n" ;

		if( !algorithm_options.use_clustering ) {
			if( options().check( "-output-sequences" )) {
				output_translated_sequences(
					segmentations,
					options().get< std::string >( "-output-sequences" ),
					kmer_pairs,
					algorithm_options.truncate_at_stops
				) ;
			}
			return ;
		}

		ui().logger() << "++ Computing pairwise alignments...\n" ;

		PairwiseAlignments alignments ;
		{
			auto progress = ui().get_progress_context( "Pairwise aligning" ) ;
			std::size_t total_reads = ([&data]() -> std::size_t {
				std::size_t result = 0 ;
				for( std::size_t i = 0; i < data.hpc_sequences().size(); ++i ) {
					result += data.count_reads_for_hpc_sequence(i) ;
				}
				return result ;
			})() ;
			auto filter_candidates = [&data,&algorithm_options,total_reads](std::size_t i)->bool {
				auto count = data.count_reads_for_hpc_sequence(i) ;
				return
					(count >= algorithm_options.min_obs_per_sample)
					&&
					(double(count) / double(total_reads) >= algorithm_options.min_fraction_per_sample)
				;
			} ;
			alignments.add_sequences(
				data.hpc_sequences(),
				[]( AlgorithmData::SequenceToIds const& elt ) { return elt.sequence ; },
				// Only align to sequences seen in enough samples
				filter_candidates,
				[&progress](std::size_t i, std::size_t j)->void { progress(i,j) ; }
			) ;
		}

		ui().logger() << "++ Ok, a total of " << alignments.size() << " alignments to " << alignments.alignment_targets().size() << " targets computed.\n" ;
		
		if( options().check( "-output-alignments" )) {
			output_alignments(
				data,
				alignments,
				options().get< std::string >( "-output-alignments" ),
				kmer_pairs
			) ;
		}

		ui().logger() << "++ Computing clusters...\n" ;
		StateLL const clusters = cluster_haplotypes( data, alignments, algorithm_options ) ;
		std::vector< SequenceIndex > const final_haplotypes = clusters.state.haplotypes() ;
		ui().logger() << "++ ...ok, " << clusters.state.size() << " clusters identified.\n" ;

		ui().logger() << "++ Computing hpc sequence-cluster identity...\n" ;
		auto const identities = compute_identities( data, alignments, clusters.state, algorithm_options ) ;

		ui().logger() << "++ Assigning hpc sequences to clusters...\n" ;
		auto hpc_assignments = std::vector< int >( identities.rows(), -1 ) ;
		for( int i = 0; i < identities.rows(); ++i ) {
			double max_identity = -1 ;
			int wmax_identity = 0 ;
			for( int j = 0; j < identities.cols(); ++j ) {
				if( identities(i,j) > max_identity ) {
					max_identity = identities(i,j) ;
					wmax_identity = j ;
				} else if( identities(i,j) == max_identity ) {
					ui().logger() << "!! Uh-oh, matches two states.\n" ;
					max_identity = -1 ;
					wmax_identity = 0 ;
					break ;
				}
			}
			if( max_identity >= algorithm_options.min_identity ) {
				hpc_assignments[i] = wmax_identity ;
			}
		}

		ui().logger() << "++ Outputting hpc alignment identities to \"" << options().get< std::string >( "-output-identities" ) << "\"...\n" ;
		output_hpc_assignments(
			identities,
			hpc_assignments,
			clusters.state,
			alignments,
			options().get< std::string >( "-output-identities" )
		) ;

		if( options().check( "-output-sequences" )) {
			ui().logger() << "++ Outputting sequences...\n" ;
			output_reads(
				data,
				hpc_assignments,
				options().get< std::string >( "-output-sequences" ),
				kmer_pairs
			) ;
		}

		ui().logger() << "++ Computing representative DNA sequences...\n" ;
		std::vector< AlgorithmData::SequenceToIds > const dna_consensus = find_most_common_representative_read(
			final_haplotypes,
			hpc_assignments,
			data
		) ;

		ui().logger() << "++ Translating sequence...\n" ;
		std::vector< AlgorithmData::SequenceToIds > aa_consensus ;
		{
			std::map< std::string, std::vector< std::size_t > > by_aa_sequence ;
			for( auto dna: dna_consensus ) {
				std::string aa_sequence = genfile::translate( dna.sequence, algorithm_options.truncate_at_stops ) ;
				std::vector< std::size_t >& v = by_aa_sequence[ aa_sequence ] ;
				v.insert(
					v.end(),
					dna.sequence_ids.begin(),
					dna.sequence_ids.end()
				) ;
			}
			for( auto kv: by_aa_sequence ) {
				aa_consensus.push_back(
					AlgorithmData::SequenceToIds{
						kv.first,
						kv.second
					}
				) ;
			}
			std::sort(
				aa_consensus.begin(),
				aa_consensus.end(),
				[]( AlgorithmData::SequenceToIds const& a, AlgorithmData::SequenceToIds const& b ) { return a.sequence_ids.size() > b.sequence_ids.size() ; }
			) ;
		}
		ui().logger() << "++ Outputting clusters...\n" ;
		output_consensus_sequences(
			dna_consensus,
			aa_consensus,
			data,
			algorithm_options,
			options().get< std::string >( "-output-clusters" ),
			kmer_pairs
		) ;

		return ;
	}

		StateLL cluster_haplotypes(
			AlgorithmData const& data,
			PairwiseAlignments const& alignments,
			AlgorithmOptions const& algorithm_options
		) {
			if( data.hpc_sequences().size() == 0 ) {
				return StateLL{MixtureOfHaplotypes(), 0 } ;
			}

			double const homopolymer_weight = algorithm_options.homopolymer_indel_weight ;
			auto compute_ll = [&](
				MixtureOfHaplotypes const& state,                                  // params
				AlgorithmData const& data
			) {
				double result = 0.0 ;
				std::vector< double > elts ;
				elts.reserve( state.size() ) ;
				for( SequenceIndex i = 0; i < data.hpc_sequences().size(); ++i ) {
					std::size_t const& sequence_count = data.count_reads_for_hpc_sequence(i) ;
					elts.clear() ;
					state.visit(
						[&]( SequenceIndex target_haplotype, double weight ) {
							AlignmentDetail const& alignment = alignments.alignment( i, target_haplotype ) ;
							elts.push_back( std::log( weight ) + alignment.homopolymer_corrected_score( homopolymer_weight ) ) ;
						}
					) ;
					result += sequence_count * iorek::log_sum_exp( elts.begin(), elts.end() ) ;
				}
				return result ;
			} ;

			auto compute_log_prior = [&](
				MixtureOfHaplotypes const& state,
				double p = 0.1
			) {
				// geometric distribution
				return std::log(1-p) + std::log(p) * (state.size() - 1) ;
			} ;

			// Shotgun stochastic search to find good haplotype set candidates.
			typedef moodycamel::ConcurrentQueue< MixtureOfHaplotypes > StateQueue ;
			typedef moodycamel::ConcurrentQueue< StateLL > StateLLQueue ;
			StateQueue state_queue ;
			StateLLQueue result_queue ;

			// Get the sequence counts within that sample.
			std::vector< std::thread > threads ;
			std::atomic< int > quit(0) ;

			{
				for( std::size_t i = 0; i < algorithm_options.number_of_threads; ++i ) {
					threads.push_back(
						std::thread(
							[&]() {
	#if DEBUG
								std::cerr << "!! THREAD " << std::this_thread::get_id() << ": starting.\n" ;
	#endif
								MixtureOfHaplotypes state ;
								while( !quit ) {
									bool popped = state_queue.try_dequeue( state ) ;
									if( popped ) {
										double ll = compute_ll( state, data ) ;
										double lp = compute_log_prior( state, 0.01 ) ;
										while( !result_queue.try_enqueue( StateLL{ state, ll + lp } )) {
											std::this_thread::sleep_for( std::chrono::microseconds(10) ) ;
										}
									} else {
										// nothing to pop, sleep to allow queue to fill.
										std::this_thread::sleep_for( std::chrono::microseconds(10) ) ;
									}
								}
	#if DEBUG
								std::cerr << "!! THREAD " << std::this_thread::get_id() << ": ending.\n" ;
	#endif
							}
						)
					) ;
				}
				std::cerr << "process_read(): constructing output thread...\n" ;
			}

			boost::random::mt19937 rng ;

			double const infinity = std::numeric_limits< double >::infinity() ;

			StateLL current{MixtureOfHaplotypes(), -infinity } ;
			std::unordered_map< double, StateLL > evaluations ;

			for( std::size_t iteration = 0; iteration < algorithm_options.max_clustering_iterations; ++iteration ) {
				auto state = current.state ;			
#if DEBUG
			std::cerr  << "!! iteration " << iteration << ", current state: " << state << " --- \n" ;
#endif
			// Re-sample weightings
			if( state.size() > 1 ) {
#if DEBUG
				std::cerr  << "!! trying reweightings...\n" ;
#endif
				for( std::size_t k = 0; k < 100; ++k ) {
					auto reweighted = state.resample_weights( rng ) ;
					state_queue.enqueue( reweighted ) ;
				}
			}

			if( state.size() > 0 ) {
#if DEBUG
				std::cerr  << "!! trying replacements...\n" ;
#endif
				for( auto haplotype: alignments.alignment_targets() ) {
					state.visit(
						[&state_queue, &state, &haplotype]( SequenceIndex i, std::size_t count ) {
							if( i != haplotype ) {
								state_queue.enqueue( state.replace( i, haplotype )) ;
							}
						}
					) ;
				}
			}

			// Try all ways to add entries
#if DEBUG
			std::cerr  << "!! trying additions...\n" ;
#endif
			for( auto haplotype: alignments.alignment_targets() ) {
				if( !state.contains( haplotype )) {
					state_queue.enqueue(
						state.add(
							haplotype,
							(state.size() == 0) ? 1.0 : 0.1
						)
					) ;
				}
			}

			// Try all ways to remove entries
			std::cerr  << "!! trying removals...\n" ;
			if( state.size() > 1 ) {
				state.visit(
					[&state_queue, &state]( SequenceIndex i, std::size_t count ) {
						state_queue.enqueue( state.remove( i ) ) ;
					}
				) ;
			}

			{
				StateLL new_state = current ;
				while( (state_queue.size_approx() > 0) || (result_queue.size_approx() > 0) ) {
#if DEBUG > 1
				std::cerr << "!! State queue:" << state_queue.size_approx() << "; result queue:" << result_queue.size_approx() << ".\n" ;
#endif
					StateLL result ;
					bool popped = result_queue.try_dequeue( result ) ;
					if( popped ) {
#if DEBUG > 1
						std::cerr << "++ RESULT: "
							<< result.state
							<< ": " << result.ll << "\n" ;
#endif
						evaluations[ result.ll ] = result ;
						if( result.ll > new_state.ll ) {
							new_state = result ;
						}
						if( result.state.contains(0)) {
							std::cerr << "++ 0 state: "
									  << result.state
									  << " (" << result.ll << ")...\n" ;
						}

					} else {
						// nothing to pop, sleep to allow queue to fill.
						std::this_thread::sleep_for( std::chrono::microseconds(10) ) ;
					}
				}

				std::cerr << "++ new state: "
					<< new_state.state
					<< " (" << new_state.ll << ")...\n" ;
				current = new_state ;
			}
		}

		{
			std::this_thread::sleep_for( std::chrono::milliseconds(100)) ;
			quit = 1 ;
			std::this_thread::sleep_for( std::chrono::milliseconds(100)) ;
			for( std::size_t i = 0; i < threads.size(); ++i ) {
				threads[i].join() ;
			}
		}

		std::cerr << "-------\n" ;
		std::cerr << "++ Final state:\n" ;
		std::cerr << current.state << ": " << current.ll << ".\n" ;
		return current ;
	}

	std::vector< AlgorithmData::SequenceToIds > find_most_common_representative_read(
		std::vector< std::size_t > const& final_haplotypes,
		std::vector< int > const& hpc_assignments,
		AlgorithmData const& data
	) {
		typedef AlgorithmData::SequenceToIds SequenceToIds ;
		std::vector< SequenceToIds > result = std::vector< SequenceToIds >( final_haplotypes.size(), SequenceToIds() ) ;
		for( int i = 0; i < hpc_assignments.size(); ++i ) {
			if( hpc_assignments[i] != -1 ) {
				std::size_t j = hpc_assignments[i] ;
				result[j].sequence_ids.insert(
					result[j].sequence_ids.end(),
					data.hpc_sequences()[i].sequence_ids.begin(),
					data.hpc_sequences()[i].sequence_ids.end()
				) ;
			}
		}
		for( std::size_t i = 0; i < result.size(); ++i ) {
			// order sequence by read count, descending order
			std::sort(
				result[i].sequence_ids.begin(),
				result[i].sequence_ids.end(),
				[&data]( std::size_t i, std::size_t j ) {
					return data.sequences()[i].reads.size() > data.sequences()[j].reads.size() ;
				}
			) ;
			if( result[i].sequence_ids.size() > 0 ) {
				result[i].sequence = data.sequences()[ result[i].sequence_ids.front() ].sequence.matching_sequence() ;
			}
		}
		return result ;
	}

	std::vector< impl::KmerPair > load_kmer_pairs( std::vector< std::string > const& kmers ) const {
		std::vector< impl::KmerPair > result ;

		using genfile::string_utils::to_string ;
		if( kmers.size() % 2 != 0 ) {
			throw genfile::BadArgumentError(
				"TranslatoratorApplication::load_kmer_pairs()",
				"kmers",
				"Expected there to be an even number of kmers (found " + to_string(kmers.size()) + ")"
			) ;
		}

		for( std::size_t i = 0; i < kmers.size(); i += 2 ) {
			result.push_back( impl::KmerPair( impl::to_upper(kmers[i]), impl::to_upper(kmers[i+1]) )) ;
		}
		return result ;
	}

	void load_excluded_reads( std::string const& filename, std::unordered_set< std::string >* result ) const {
		auto stream = genfile::open_text_file_for_input( filename ) ;
		std::string line ;
		while( std::getline( *stream, line )) {
			result->insert( line ) ;
		}
	}

	Eigen::MatrixXd compute_identities(
		AlgorithmData const& data,
		PairwiseAlignments const& alignments,
		MixtureOfHaplotypes const& haplotypes,
		AlgorithmOptions const& algorithm_options
	) {
		// Assign each read sequence to a target state
		Eigen::MatrixXd result(
			data.hpc_sequences().size(),
			haplotypes.size()
		) ;
		for( SequenceIndex i = 0; i < data.hpc_sequences().size(); ++i ) {
			std::vector< SequenceIndex > target_haplotypes = haplotypes.haplotypes() ;
			for( std::size_t j = 0; j < target_haplotypes.size(); ++j ) {
				SequenceIndex target = target_haplotypes[j] ;
				AlignmentDetail const& alignment = alignments.alignment( i, target ) ;
				result(i,j) = double( alignment.identity ) ;
			}
		}
		return result ;
	}

	void output_hpc_assignments(
		Eigen::MatrixXd const& identities,
		std::vector< int > const& assignments,
		MixtureOfHaplotypes const& state,
		PairwiseAlignments const& alignments,
		std::string const& filename
	) const {
		using genfile::string_utils::to_string ;
		statfile::BuiltInTypeStatSink::UniquePtr
			output = statfile::BuiltInTypeStatSink::open( filename ) ;
		{
			output->write_comment( "Written by translatorator" ) ;
//			output->write_comment( "Kmer pairs are:" ) ;
//			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
//				output->write_comment( to_string(i+1) + ": " + kmer_pairs[i].first() + " / " + kmer_pairs[i].second() ) ;
//			}
			(*output) | "hpc_id" | "best_cluster_id" | "best_alignment_score" | "best_alignment_cigar" ;
			for( int j = 0; j < identities.cols(); ++j ) {
				(*output) | ("alignment_score:cluster_" + to_string(j)) ;
			}
			for( int j = 0; j < identities.cols(); ++j ) {
				(*output) | ("identity:cluster_" + to_string(j)) ;
			}
		}
		auto NA = genfile::MissingValue() ;
		std::vector< SequenceIndex > target_haplotypes = state.haplotypes() ;
		double homopolymer_weight = options().get< double >( "-homopolymer-indel-weight" ) ;
		for( int i = 0; i < identities.rows(); ++i ) {
			(*output)
				<< int64_t(i)
				<< int64_t( assignments[i] ) ;
			if( assignments[i] >= 0 ) {
				(*output)
					<< alignments.alignment( i, target_haplotypes[assignments[i]] ).homopolymer_corrected_score( homopolymer_weight )
					<< alignments.alignment( i, target_haplotypes[assignments[i]] ).cigar
				;
				for( int j = 0; j < identities.cols(); ++j ) {
					(*output) << alignments.alignment( i, target_haplotypes[j] ).homopolymer_corrected_score( homopolymer_weight ) ;
				}
			} else {
				(*output) << NA << NA ;
				for( int j = 0; j < identities.cols(); ++j ) {
					(*output) << NA ;
				}
			}
			for( int j = 0; j < identities.cols(); ++j ) {
				(*output) << identities(i,j) ;
			}
			(*output) << statfile::end_row() ;
		}
	}

	void output_translated_sequences(
		std::vector< Segmentation > const& result,
		std::string const& filename,
		std::vector< impl::KmerPair > kmer_pairs,
		bool truncate_at_stops
	) const {
		using genfile::string_utils::to_string ;
		statfile::BuiltInTypeStatSink::UniquePtr
			output = statfile::BuiltInTypeStatSink::open( filename ) ;
		{
			output->write_comment( "Written by translatorator" ) ;
			output->write_comment( "Kmer pairs are:" ) ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				output->write_comment( to_string(i+1) + ": " + kmer_pairs[i].first() + " / " + kmer_pairs[i].second() ) ;
			}
			(*output) | "file" | "read_id" | "strand" ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				(*output) | ("start_" + to_string(i+1)) | ("end_" + to_string(i+1)) ;
			}
			(*output) | "dna_sequence" ;
			(*output) | "aa_sequence" ;
		}

		for( auto s: result ) {
#if DEBUG > 1
			std::cerr << "kmer pairs size: " << kmer_pairs.size() << ".\n" ;
			std::cerr << s << "\n" ;
#endif
			(*output)
				<< s.sample_id()
				<< s.sequence_id()
				<< std::string( 1, s.strand() ) ;

			if( s.is_unambiguous() ) {
				for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
					(*output)
						<< uint64_t(s.ranges()[i].start + 1)
						<< uint64_t(s.ranges()[i].end) ;
				}
				(*output) << s.matching_sequence() ;
				(*output) << genfile::translate( s.matching_sequence(), truncate_at_stops ) ;
			} else {
				while( output->current_column() < output->number_of_columns() ) {
					(*output) << "NA" ;
				}
			}

			(*output) << statfile::end_row() ;
		}
	}

	void output_reads(
		AlgorithmData const& data,
		std::vector< int > const& assignments,
		std::string const& filename,
		std::vector< impl::KmerPair > kmer_pairs
	) const {
		using genfile::string_utils::to_string ;
		statfile::BuiltInTypeStatSink::UniquePtr
			output = statfile::BuiltInTypeStatSink::open( filename ) ;
		{
			output->write_comment( "Written by translatorator" ) ;
			output->write_comment( "Kmer pairs are:" ) ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				output->write_comment( to_string(i+1) + ": " + kmer_pairs[i].first() + " / " + kmer_pairs[i].second() ) ;
			}
			(*output) | "read_id" | "sequence_id" | "hpc_id" | "cluster_id" | "sequence_count" | "strand" | "hpc_sequence_count" ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				(*output)
					| (boost::format( "start_%d" ) % (i+1)).str()
					| (boost::format( "end_%d" ) % (i+1)).str()
				;
			}
			(*output) | "sequence" | "hpc_sequence" ;
		}

		auto NA = genfile::MissingValue() ;
		for( std::size_t i = 0; i < data.hpc_sequences().size(); ++i ) {
			auto const& hpc = data.hpc_sequences()[i] ;
			for( std::size_t j = 0; j < hpc.sequence_ids.size(); ++j ) {
				std::size_t sequence_id = hpc.sequence_ids[j] ;
				auto const& segmentations = data.sequences()[sequence_id] ;
				for( auto read: segmentations.reads ) {
					(*output)
						<< read.sequence_id()
						<< uint64_t(sequence_id)
						<< uint64_t(i)
						<< ((assignments[i] >= 0) ? to_string(assignments[i]) : "NA" )
						<< uint64_t( segmentations.reads.size() )
						<< std::string( 1, char(read.strand()) )
						<< uint64_t(hpc.sequence_ids.size()) ;
					for( std::size_t k = 0; k < kmer_pairs.size(); ++k ) {
						(*output)
							<< uint64_t( read.ranges()[k].start )
							<< uint64_t( read.ranges()[k].end ) ;
					}
					
					(*output)
						<< segmentations.sequence.matching_sequence()
						<< hpc.sequence
						<< statfile::end_row()
					;
				}
			}
		}

		for( auto read: data.ambiguous_sequences() ) {
			(*output)
				<< read.sequence_id()
				<< NA
				<< NA
				<< NA
				<< NA
				<< std::string( 1, char(read.strand()) )
				<< NA ;
			(*output)
				<< uint64_t( read.ranges()[0].start )
				<< uint64_t( read.ranges()[0].end ) ;
			for( std::size_t k = 1; k < kmer_pairs.size(); ++k ) {
				(*output) << NA << NA ;
			}
			(*output) << read.matching_sequence() << NA << statfile::end_row() ;
		}
	}

	void output_alignments(
		AlgorithmData const& data,
		PairwiseAlignments const& alignments,
		std::string const& filename,
		std::vector< impl::KmerPair > kmer_pairs
	) const {
		using genfile::string_utils::to_string ;
		statfile::BuiltInTypeStatSink::UniquePtr
		output = statfile::BuiltInTypeStatSink::open( filename ) ;
		{
			output->write_comment( "Written by translatorator" ) ;
			output->write_comment( "Kmer pairs are:" ) ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				output->write_comment( to_string(i+1) + ": " + kmer_pairs[i].first() + " / " + kmer_pairs[i].second() ) ;
			}
			(*output)
				| "hpc_id" | "read_count" | "target_id"
				| "sequence_length" | "target_sequence_length"
				| "alignment_length" | "alignment_score"
				| "hp_adjusted_alignment_score" | "cigar"
			;
		}

		auto count_reads_for_hpc_sequence = [&data]( std::size_t i ) {
			auto result = 0ul ;
			auto uncompressed_sequences = data.hpc_sequences()[i].sequence_ids ;
			for( auto j: data.hpc_sequences()[i].sequence_ids ) {
				result += data.sequences()[j].reads.size() ;
			}
			return result ;
		} ;
		auto alignment_targets = alignments.alignment_targets() ;

		double homopolymer_weight = options().get< double >( "-homopolymer-indel-weight" ) ;
		for( SequenceIndex i = 0; i < data.hpc_sequences().size(); ++i ) {
			auto const read_count = count_reads_for_hpc_sequence(i) ;
			for( auto j: alignment_targets ) {
				auto alignment = alignments.alignment(i,j) ;
				(*output)
					<< uint32_t(i)
					<< uint32_t(read_count)
					<< uint32_t(j)
					<< uint32_t(alignment.a.size())
					<< uint32_t(alignment.b.size())
					<< uint32_t(alignment.long_form_cigar.size())
					<< alignment.score
					<< alignment.homopolymer_corrected_score( homopolymer_weight )
					<< alignment.cigar
					<< statfile::end_row() ;
			}

		}
	}

	void output_consensus_sequences(
		std::vector< AlgorithmData::SequenceToIds > const& dna,
		std::vector< AlgorithmData::SequenceToIds > const& aa,
		AlgorithmData const& data,
		AlgorithmOptions const& algorithm_options,
		std::string const& filename,
		std::vector< impl::KmerPair > kmer_pairs
	) {
		using genfile::string_utils::to_string ;
		statfile::BuiltInTypeStatSink::UniquePtr
			output = statfile::BuiltInTypeStatSink::open( filename ) ;
		{
			output->write_comment( "Written by translatorator" ) ;
			output->write_comment( "Kmer pairs are:" ) ;
			for( std::size_t i = 0; i < kmer_pairs.size(); ++i ) {
				output->write_comment( to_string(i+1) + ": " + kmer_pairs[i].first() + " / " + kmer_pairs[i].second() ) ;
			}
			(*output) | "file" | "type" | "cluster_id" | "hpc_id" | "supporting_reads" | "exact_reads" | "total_informative_reads" | "proportion" | "total_reads" | "sequence" ;
		}

		std::size_t total_informative_reads = 0 ;
		for( auto x: dna ) {
			for( auto i: x.sequence_ids ) {
				auto const& y = data.sequences()[i] ;
				total_informative_reads += y.reads.size() ;
			}
		}

		std::string sample_id = "" ;
		if( data.sequences().size() > 0 ) {
			sample_id = data.sequences()[0].reads[0].sample_id() ;
		}
		for( std::size_t i = 0; i < dna.size(); ++i ) {
			auto x = dna[i] ;
			auto total_reads = 0ul ;
			auto total_exact = 0ul ;
			for( auto i: x.sequence_ids ) {
				auto const& y = data.sequences()[i] ;
				auto const& sequence = y.sequence.matching_sequence() ;
				total_reads += y.reads.size() ;
				if( sequence == x.sequence) {
					total_exact += y.reads.size() ;
				}
			} ;
			(*output)
				<< sample_id
				<< "dna"
				<< int64_t(i)
				<< int64_t( x.sequence_ids[0] )
				<< int64_t( total_reads )
				<< int64_t( total_exact )
				<< int64_t( total_informative_reads )
				<< double( total_reads ) / double( total_informative_reads )
				<< int64_t( data.total_reads() )
				<< x.sequence
				<< statfile::end_row()
			;
		}

		for( std::size_t i = 0; i < aa.size(); ++i ) {
			auto x = aa[i] ;
			auto total_reads = 0ul ;
			auto total_exact = 0ul ;
			for( auto i: x.sequence_ids ) {
				auto const& y = data.sequences()[i] ;
				auto const sequence = genfile::translate( y.sequence.matching_sequence(), algorithm_options.truncate_at_stops ) ;
				total_reads += y.reads.size() ;
				if( sequence == x.sequence ) {
					total_exact += y.reads.size() ;
				}
			} ;
			(*output)
				<< sample_id
				<< "aa"
				<< int64_t(i)
				<< int64_t( x.sequence_ids[0] )
				<< int64_t( x.sequence_ids.size() )
				<< int64_t( total_exact )
				<< int64_t( total_informative_reads )
				<< double( total_reads ) / double( total_informative_reads )
				<< int64_t( data.total_reads() )
				<< x.sequence
				<< statfile::end_row()
			;
		}

	}

	Regions get_regions( std::vector< std::string > const& specs ) const {
		Regions result ;
		for( auto spec: specs ) {
			genfile::GenomePositionRange region = genfile::GenomePositionRange::parse( spec ).toZeroBased() ;
			if( !region.has_chromosome() ) {
				throw genfile::BadArgumentError(
					"TranslatoratorApplication::get_regions()",
					"-training-regions=\"" + spec + "\"",
					"Regions must be specified with chromosome/contig identifiers."
				) ;
			}
			result.push_back( region ) ;
		}
		return result ;
	}
	typedef std::function< bool( std::string const& name, std::string const& sequence, std::string const& qualities ) > ReadFilter ;
	void find_segmentations(
		std::vector< std::string > const& filenames,
		ReadFilter include_read,
		std::vector< impl::KmerPair > const& kmer_pairs,
		std::vector< Segmentation >* result
	) {
		using genfile::string_utils::to_string ;
		auto progress_context = ui().get_progress_context( "Loading sequences" ) ;
		std::vector< std::string > const& names = get_names_from_filenames(filenames) ;
		for( std::size_t i = 0; i < filenames.size(); ++i ) {
			if( options().check( "-range" )) {
				Regions regions = get_regions( options().get_values< std::string >( "-range" ) ) ;
				// Only bam/sam/cram files are supported if -range is given
				impl::BamSequenceProvider::UniquePtr sequences ;
				if( options().check( "-reference" )) {
					sequences = impl::BamSequenceProvider::open( filenames[i], options().get< std::string >( "-reference" )) ;
				} else {
					sequences = impl::BamSequenceProvider::open( filenames[i] ) ;
				}
				for( auto const& region: regions ) {
					sequences->set_region( region ) ;
					find_segmentations(
						*sequences,
						names[i],
						kmer_pairs,
						include_read,
						result
					) ;
				}
			} else {
				impl::SequenceProvider::UniquePtr sequences = impl::SequenceProvider::open( filenames[i] ) ;
				find_segmentations(
					*sequences,
					names[i],
					kmer_pairs,
					include_read,
					result
				) ;
			}
			progress_context( i+1, names.size() ) ;
		}
	}
	
	void find_segmentations(
		impl::SequenceProvider& sequences,
		std::string const& name,
		std::vector< impl::KmerPair > kmer_pairs,
		ReadFilter include_read,
		std::vector< Segmentation >* result
	) const {
		try {
			find_segmentations_unsafe( sequences, name, kmer_pairs, include_read, result ) ;
		} catch( std::exception const& e ) {
			ui().logger() << "!! Error processing \"" << name << "\", there will be no results for this file.\n" ;
		}
	}

	void find_segmentations_unsafe(
		impl::SequenceProvider& sequences,
		std::string const& name,
		std::vector< impl::KmerPair > const& kmer_pairs,
		ReadFilter include_read,
		std::vector< Segmentation >* result
	) const {
		std::string sequence_name ;
		std::string sequence ;
		std::string fwd_sequence, rc_sequence ;
		impl::Segmentation::Ranges fwd_positions, rc_positions ;
		std::string qualities ;
		while( sequences.next( &sequence_name, &sequence, &qualities )) {
			if( include_read( sequence_name, sequence, qualities )) {
				impl::to_upper_inplace( sequence ) ;
				bool fwd = load_fragmented_dna_sequence( sequence, kmer_pairs, &fwd_sequence, &fwd_positions ) ;
				bool rev = load_fragmented_dna_sequence( genfile::reverse_complement( sequence ), kmer_pairs, &rc_sequence, &rc_positions ) ;
				if( fwd & rev ) {
					result->push_back(
						impl::Segmentation(
							name,
							sequence_name,
							impl::Segmentation::eAmbiguousStrand,
							sequence,
							impl::Segmentation::Ranges( 1, impl::SegmentedSequence::Range( 0, sequence.size() ))
						)
					) ;
				} else if( fwd ) {
					result->push_back(
						impl::Segmentation(
							name,
							sequence_name,
							impl::Segmentation::eFwdStrand,
							fwd_sequence,
							fwd_positions
						)
					) ;
				} else if( rev ) {
					result->push_back(
						impl::Segmentation(
							name,
							sequence_name,
							impl::Segmentation::eRevStrand,
							rc_sequence,
							rc_positions
						)
					) ;
				}
				if( !fwd && !rev ) {
					result->push_back(
						impl::Segmentation(
							name,
							sequence_name,
							impl::Segmentation::eNeitherStrand,
							sequence,
							impl::Segmentation::Ranges( 1, impl::SegmentedSequence::Range( 0, sequence.size() ))
						)
					) ;
				}
			}
		}
	}
	
	std::vector< std::string > get_names_from_filenames( std::vector< std::string > const& filenames ) {
		std::vector< std::string > result ;
		for( auto s: filenames ) {
			boost::filesystem::path p( s ) ;
			result.push_back( p.stem().string() ) ;
		}
		return result ;
	}
} ;

int main( int argc, char** argv )
{
	std::ios_base::sync_with_stdio( false ) ;
	try {
		TranslatoratorApplication app( argc, argv ) ;
		app.run() ;
	}
	catch( appcontext::HaltProgramWithReturnCode const& e ) {
		return e.return_code() ;
	}
	return 0 ;
}
	
