def configure( cfg ):
	pass
	
def build( bld ):
	bld.program(
		source = "coverotron.cpp",
		target = 'coverotron',
		use = 'seqan bamtools seqlib package_revision appcontext genfile statfile pthread',
		includes = "./"
	)
	bld.program(
		source = "nonahore.cpp",
		target = 'nonahore',
		use = 'package_revision appcontext genfile statfile libsvelte',
		includes = "./"
	)
	bld.program(
		source = "parse-cigar.cpp",
		target = 'parse-cigar',
		use = 'seqan bamtools seqlib package_revision appcontext genfile qcdb pthread',
		includes = "./"
	)
	bld.program(
		source = "tabulate-alignments.cpp",
		target = 'tabulate-alignments',
		use = 'seqan bamtools seqlib package_revision appcontext genfile qcdb pthread',
		includes = "./"
	)
	bld.program(
		source = "classify-kmers.cpp",
		target = 'classify-kmers',
		use = 'seqan bamtools seqlib package_revision appcontext genfile qcdb pthread jellyfish',
		includes = "./"
	)
